# IncidentMind — Database Repository Interfaces
# Owner: AI / Intelligence layer (contracts); implementation: Database/Cloud team
#
# These protocols define the contract the AI layer expects from the persistence
# layer.  The AI agent always depends on these abstractions — never on a
# concrete database driver.
#
# Dependency injection point:
#   backend/db/repository_factory.py  get_repositories()
#   When USE_REAL_DB=true -> inject CockroachDB implementation
#   When USE_REAL_DB=false -> inject MockDB implementation (default)

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Outcome taxonomy
# ---------------------------------------------------------------------------

class SolutionOutcome(str, Enum):
    """
    All possible outcomes for a solution attempt.

    SUCCESS  -- the fix fully resolved the incident.
    FAILURE  -- the fix was executed but did not resolve the incident.
    PARTIAL  -- the fix improved but did not fully resolve the incident.
    REJECTED -- the solution was proposed but the engineer chose not to execute it,
               OR it was actively declined as unsuitable.
               This is NOT the same as 'unknown'.
               Ranking treats this as a mild negative signal.
    UNKNOWN  -- the outcome was never recorded or could not be verified.
               Ranking treats this as strictly neutral (0.0).
    """
    SUCCESS = "success"
    FAILURE = "failure"
    PARTIAL = "partial"
    REJECTED = "rejected"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class Incident(BaseModel):
    """Stored incident record (read from / written to persistent memory)."""
    id: str = Field(..., description="UUID string for the incident")
    title: str
    description: str
    severity: str
    category: str
    logs: Optional[str] = None
    embedding: Optional[List[float]] = None  # Generated by AI layer
    created_at: datetime = Field(default_factory=datetime.utcnow)
    resolved: bool = False
    environment: Optional[str] = None  # e.g. "production", "staging"
    reporter_id: Optional[str] = None


class SolutionAttempt(BaseModel):
    """
    A single attempt to resolve an incident.

    Critical rules (from Memory Architecture):
    - NEVER overwrite an existing attempt.
    - Every execution creates a NEW record.
    - Failed attempts must be preserved -- failure is valuable negative evidence.
    """
    id: str = Field(..., description="UUID string for the attempt")
    incident_id: str
    solution_text: str
    outcome: SolutionOutcome
    failure_reason: Optional[str] = None   # Why it failed, if known
    performed_by: Optional[str] = None     # User ID or "ai_agent"
    execution_duration_ms: Optional[int] = None
    confidence_at_execution: Optional[float] = None  # AI confidence at time of attempt
    reward_delta: Optional[int] = None               # Reward adjustment if applicable
    mode: Optional[str] = Field(default="real", description="Execution mode: 'real' or 'mock'")
    created_at: datetime = Field(default_factory=datetime.utcnow)


class SimilarIncidentResult(BaseModel):
    """Returned by vector search -- combines the incident with its similarity score."""
    incident: Incident
    similarity_score: float  # Cosine similarity [0.0, 1.0]
    solution_attempts: List[SolutionAttempt] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Repository protocols
# ---------------------------------------------------------------------------

class IncidentRepository(ABC):
    """
    Abstraction over the incidents persistence store.

    REQUIRED CONTRACT for Database/Cloud team integration:
    - save_incident:            upsert-style; embedding field may be updated
    - get_incident:             return None if not found
    - search_similar_incidents: vector search using cosine similarity on the
                                stored embedding column; returns top-k results
                                ordered by similarity descending
    - list_incidents:           paginated list for admin/reporting
    """

    @abstractmethod
    def save_incident(self, incident: Incident) -> Incident:
        """Persist an incident. Returns the saved record."""
        ...

    @abstractmethod
    def get_incident(self, incident_id: str) -> Optional[Incident]:
        """Retrieve incident by ID. Returns None if not found."""
        ...

    @abstractmethod
    def search_similar_incidents(
        self,
        query_embedding: List[float],
        top_k: int = 10,
        min_similarity: float = 0.0,
    ) -> List[SimilarIncidentResult]:
        """
        Vector similarity search.

        Returns up to top_k incidents ordered by cosine similarity descending.
        Only returns incidents whose similarity >= min_similarity.
        """
        ...

    @abstractmethod
    def list_incidents(self, limit: int = 50, offset: int = 0) -> List[Incident]:
        """List incidents with pagination."""
        ...


class SolutionAttemptRepository(ABC):
    """
    Abstraction over the solution_attempts persistence store.

    CRITICAL: Never delete or overwrite existing records.
    Every call to save_attempt must INSERT a new record.

    REQUIRED CONTRACT for Database/Cloud team integration:
    - save_attempt:               insert a new attempt record
    - get_attempts_for_incident:  return all attempts for an incident, ordered
                                  by created_at descending (newest first)
    - get_attempts_for_incidents: batch fetch for multiple incident IDs
    """

    @abstractmethod
    def save_attempt(self, attempt: SolutionAttempt) -> SolutionAttempt:
        """
        Insert a new solution attempt.
        Must NEVER overwrite existing attempts -- always creates a new record.
        """
        ...

    @abstractmethod
    def get_attempts_for_incident(self, incident_id: str) -> List[SolutionAttempt]:
        """
        Return all solution attempts for a given incident ID.
        Ordered by created_at descending (most recent first).
        """
        ...

    @abstractmethod
    def get_attempts_for_incidents(
        self, incident_ids: List[str]
    ) -> dict:
        """
        Batch fetch: returns a dict mapping incident_id -> list of attempts.
        Efficient for retrieving history for multiple similar incidents at once.
        """
        ...
